name: PHP Unit Tests

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

permissions:
  contents: read

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: json, curl
        coverage: none

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run Clients Tests
      run: vendor/bin/phpunit --testsuite Clients

    - name: Run Subaccounts Tests
      run: vendor/bin/phpunit --testsuite Subaccounts

    - name: Run All Unit Tests
      run: vendor/bin/phpunit --testsuite Unit
